name: course_app
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_mobx: ^1.1.0
  provider: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.5
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0

# gera o nome da aplicação
# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "Courses"

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpeg
    - assets/images/background.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
